// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230329162622_RobotAPICreate1")]
    partial class RobotAPICreate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Domain.Payload", b =>
                {
                    b.Property<int>("payloadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("batteryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("distanceToGoal")
                        .HasColumnType("REAL");

                    b.HasKey("payloadId");

                    b.ToTable("Payloads");
                });

            modelBuilder.Entity("Domain.Robot", b =>
                {
                    b.Property<int>("robotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("batteryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("distanceToGoal")
                        .HasColumnType("REAL");

                    b.HasKey("robotId");

                    b.ToTable("Robots");
                });
#pragma warning restore 612, 618
        }
    }
}
